sudo: false
language: node_js
install:
  - travis_retry gem install s3_website -v 3.4.0
  - travis_retry pip install awscli --upgrade --user
  - travis_retry npm install
before_script: webpack
script: ./s3_deploy.sh
cache:
  yarn: true
  bundler: true
  directories:
    - node_modules